# Generated by Django 6.0 on 2025-12-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('archivo_soat', models.FileField(upload_to='soportes_soat/')),
                ('placa_detectada', models.CharField(blank=True, max_length=10, null=True)),
                ('monto_detectado', models.CharField(blank=True, max_length=50, null=True)),
                ('resultado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Análisis'), ('APROBADO', 'Aprobado'), ('FRAUDE', 'Posible Fraude')], default='PENDIENTE', max_length=20)),
            ],
        ),
    ]
